app:
  baseUrl: https://mpairavat.in/learningPortal

spring:
  application:
    name: SpringJwtSecurity3XWithOauth
  datasource:
    username: root
    password: sail
    url: jdbc:mysql://localhost:3306/jwtsecurity3x
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: false
#outh2 google login        
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ********************************************
            client-secret: ***************************************
            redirect-uri: "${app.baseUrl}/login/oauth2/code/google"
            scope: email,profile
            authorization-grant-type: authorization_code
          github:
            client-id: *****************************************
            client-secret: *************************************
            redirect-uri: "${app.baseUrl}/login/oauth2/code/github"
            scope: read:user, user:email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo  

#        see it from drive springboot manaual deployment docs
            

ui.domain.path: http://localhost:3000/