spring:
  application:
    name: SpringJwtSecurity3XWithOauth
  datasource:
    username: root
    password: sail
    url: jdbc:mysql://localhost:3306/jwtsecurity3x
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        show_sql: false
#outh2 google login        
  security:
    oauth2:
      client:
        registration:
#        see it from drive docs
            

ui.domain.path: http://localhost:3000/